### ISSUE TITLE
Error of `double free or corruption (out)` for `subisomorphic_lad`

### ISSUE THREAD

**Issue by Edenharder** [igraph/python-igraph#228]
- [x] This issue is for the Python interface of igraph.
- [x] This issue is a bug report or a feature request, not a support question.

Python: 3.6, python-igraph:0.7.1.post6, Operating system: Manjaro 18.0.4 or CentOS 7.4.1708

Extra information: same version of Python and python-igraph work well in Mac OS 10.11.6

## Minimal example
```
from igraph import *
eds = [(0, 4), (0, 5), (0, 6), (1, 4), (1, 5), (1, 6), (2, 5), (3, 6)] 
seds = [(0, 4), (0, 5), (1, 5), (1, 6),(2, 6), (3, 6)] 
gh = Graph(eds)
sgh = Graph(seds)
print(gh.subisomorphic_lad(sgh))
```
## Errors
```
double free or corruption (out): 0x0000000000868c20 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7c619)[0x2aaaabdb5619]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_free+0x18)[0x2aaab2d3ba30]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_i_lad_ensureGACallDiff+0xa94)[0x2aaab2e98e5f]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_i_lad_filter+0x241)[0x2aaab2e99d75]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_i_lad_solve+0x16b)[0x2aaab2e99f17]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_i_lad_solve+0x76b)[0x2aaab2e9a517]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/../../../libigraph.so.0(igraph_subisomorphic_lad+0x4c9)[0x2aaab2e9ab58]
/home/xuser/anaconda3/lib/python3.6/site-packages/igraph/_igraph.cpython-36m-x86_64-linux-gnu.so(igraphmodule_Graph_subisomorphic_lad+0x113)[0x2aaab2987cc3]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(_PyCFunction_FastCallDict+0x22d)[0x2aaaaad9b08d]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(+0x16549a)[0x2aaaaae3449a]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(_PyEval_EvalFrameDefault+0x3a5c)[0x2aaaaae3871c]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(+0x16509e)[0x2aaaaae3409e]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(PyEval_EvalCodeEx+0x6d)[0x2aaaaae346cd]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(PyEval_EvalCode+0x3b)[0x2aaaaae3471b]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(PyRun_FileExFlags+0xb2)[0x2aaaaae700a2]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(PyRun_SimpleFileExFlags+0xe7)[0x2aaaaae70207]
/home/xuser/anaconda3/bin/../lib/libpython3.6m.so.1.0(Py_Main+0xe9d)[0x2aaaaae8c6fd]
/home/xuser/anaconda3/bin/python3(main+0x16c)[0x400bbc]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x2aaaabd5ac05]
/home/xuser/anaconda3/bin/python3[0x400c7d]
======= Memory map: ========
00400000-00401000 r-xp 00000000 00:28 929774209                          /home/xuser/anaconda3/bin/python3.6
00601000-00602000 rw-p 00001000 00:28 929774209                          /home/xuser/anaconda3/bin/python3.6
00602000-0088c000 rw-p 00000000 00:00 0                                  [heap]
2aaaaaaab000-2aaaaaacc000 r-xp 00000000 08:01 105755429                  /usr/lib64/ld-2.17.so
2aaaaaacc000-2aaaaaace000 r-xp 00000000 00:00 0                          [vdso]
2aaaaaace000-2aaaaaacf000 rw-p 00000000 00:00 0 
2aaaaaacf000-2aaaaaad6000 r--s 00000000 08:01 69718506                   /usr/lib64/gconv/gconv-modules.cache
2aaaaaad6000-2aaaaaad7000 rw-p 00000000 00:00 0 
2aaaaaae7000-2aaaaac6c000 rw-p 00000000 00:00 0 
2aaaaac91000-2aaaaac94000 r--p 00000000 00:28 881293753                  /home/xuser/anaconda3/lib/libgcc_s.so.1
2aaaaac94000-2aaaaaca1000 r-xp 00003000 00:28 881293753                  /home/xuser/anaconda3/lib/libgcc_s.so.1
2aaaaaca1000-2aaaaaca4000 r--p 00010000 00:28 881293753                  /home/xuser/anaconda3/lib/libgcc_s.so.1
2aaaaaca4000-2aaaaaca5000 r--p 00012000 00:28 881293753                  /home/xuser/anaconda3/lib/libgcc_s.so.1
2aaaaaca5000-2aaaaaca6000 rw-p 00013000 00:28 881293753                  /home/xuser/anaconda3/lib/libgcc_s.so.1
2aaaaaccc000-2aaaaaccd000 r--p 00021000 08:01 105755429                  /usr/lib64/ld-2.17.so
2aaaaaccd000-2aaaaacce000 rw-p 00022000 08:01 105755429                  /usr/lib64/ld-2.17.so
2aaaaacce000-2aaaaaccf000 rw-p 00000000 00:00 0 
2aaaaaccf000-2aaaaaf72000 r-xp 00000000 00:28 914770321                  /home/xuser/anaconda3/lib/libpython3.6m.so.1.0
2aaaaaf72000-2aaaab172000 ---p 002a3000 00:28 914770321                  /home/xuser/anaconda3/lib/libpython3.6m.so.1.0
2aaaab172000-2aaaab1db000 rw-p 002a3000 00:28 914770321                  /home/xuser/anaconda3/lib/libpython3.6m.so.1.0
2aaaab1db000-2aaaab20c000 rw-p 00000000 00:00 0 
2aaaab20c000-2aaaab223000 r-xp 00000000 08:01 106355508                  /usr/lib64/libpthread-2.17.so
2aaaab223000-2aaaab422000 ---p 00017000 08:01 106355508                  /usr/lib64/libpthread-2.17.so
2aaaab422000-2aaaab423000 r--p 00016000 08:01 106355508                  /usr/lib64/libpthread-2.17.so
2aaaab423000-2aaaab424000 rw-p 00017000 08:01 106355508                  /usr/lib64/libpthread-2.17.so
2aaaab424000-2aaaab428000 rw-p 00000000 00:00 0 
2aaaab428000-2aaaab42a000 r-xp 00000000 08:01 106020472                  /usr/lib64/libdl-2.17.so
2aaaab42a000-2aaaab62a000 ---p 00002000 08:01 106020472                  /usr/lib64/libdl-2.17.so
2aaaab62a000-2aaaab62b000 r--p 00002000 08:01 106020472                  /usr/lib64/libdl-2.17.so
2aaaab62b000-2aaaab62c000 rw-p 00003000 08:01 106020472                  /usr/lib64/libdl-2.17.so
2aaaab62c000-2aaaab62e000 r-xp 00000000 08:01 106448700                  /usr/lib64/libutil-2.17.so
2aaaab62e000-2aaaab82d000 ---p 00002000 08:01 106448700                  /usr/lib64/libutil-2.17.so
2aaaab82d000-2aaaab82e000 r--p 00001000 08:01 106448700                  /usr/lib64/libutil-2.17.so
2aaaab82e000-2aaaab82f000 rw-p 00002000 08:01 106448700                  /usr/lib64/libutil-2.17.so
2aaaab82f000-2aaaab836000 r-xp 00000000 08:01 106423539                  /usr/lib64/librt-2.17.so
2aaaab836000-2aaaaba35000 ---p 00007000 08:01 106423539                  /usr/lib64/librt-2.17.so
2aaaaba35000-2aaaaba36000 r--p 00006000 08:01 106423539                  /usr/lib64/librt-2.17.so
2aaaaba36000-2aaaaba37000 rw-p 00007000 08:01 106423539                  /usr/lib64/librt-2.17.so
2aaaaba37000-2aaaabb38000 r-xp 00000000 08:01 106167177                  /usr/lib64/libm-2.17.so
2aaaabb38000-2aaaabd37000 ---p 00101000 08:01 106167177                  /usr/lib64/libm-2.17.so
2aaaabd37000-2aaaabd38000 r--p 00100000 08:01 106167177                  /usr/lib64/libm-2.17.so
2aaaabd38000-2aaaabd39000 rw-p 00101000 08:01 106167177                  /usr/lib64/libm-2.17.so
2aaaabd39000-2aaaabef1000 r-xp 00000000 08:01 105915347                  /usr/lib64/libc-2.17.so
2aaaabef1000-2aaaac0f1000 ---p 001b8000 08:01 105915347                  /usr/lib64/libc-2.17.so
2aaaac0f1000-2aaaac0f5000 r--p 001b8000 08:01 105915347                  /usr/lib64/libc-2.17.so
2aaaac0f5000-2aaaac0f7000 rw-p 001bc000 08:01 105915347                  /usr/lib64/libc-2.17.so
2aaaac0f7000-2aaaac0fc000 rw-p 00000000 00:00 0 
2aaaac0fc000-2aaab2623000 r--p 00000000 08:01 35026700                   /usr/lib/locale/locale-archive
2aaab2623000-2aaab26a3000 rw-p 00000000 00:00 0 Aborted
```

**Comment by vtraag** [comment]
I can confirm this issue on Ubuntu 19.04, using `python-igraph` `0.7.1-post6`. The problem seems to have been solved in the latest version in the `master` branch though.

**Comment by Edenharder** [comment]
@vtraag Thank you for your information! When I tried to install the master branch via pip, I come across the error `Failed building wheel for python-igraph`. Can I have your suggestion?

**Comment by vtraag** [comment]
Yes, of course! Sorry, I was just looking at the bug, and trying to see what should be solved.

You have to compile the package yourself, so be sure that your build tools are installed. You should be able to install and compile as explained [here](https://github.com/igraph/python-igraph/blob/master/README.md#compiling-the-development-version) in the README.

**Comment by vtraag** [comment]
We'll close this issue, it is fixed in https://github.com/igraph/igraph/pull/1164.

**Comment by Edenharder** [comment]
@vtraag I have followed your suggestion to install the `master` branch on Manjaro linux with Python 3.7.3, it seems that the problem is still there. The error information is 
```
double free or corruption (out)
[1]    10726 abort (core dumped)
```

**Comment by szhorvat** [comment]
Just to be clear, did you only use the `master` branch of _this_ repository (python-igraph)?

It is important to compile with the master branch of [the igraph C core](https://github.com/igraph/igraph/). See here:

https://github.com/igraph/python-igraph/blob/master/README.md#compiling-the-development-version

**Comment by Edenharder** [comment]
@szhorvat I think so, what I did was
```
python-igraph git:(master) ✗ python setup.py develop --c-core-url https://github.com/igraph/igraph/archive/master.tar.gz
```
Because I use a virtual environment of python, so `sudo` is unnecessary.

**Comment by vtraag** [comment]
You seem to be using Anaconda, perhaps `igraph` (i.e. the C core) was still installed? You can explicitly uninstall `conda uninstall igraph` in addition to `conda uninstall python-igraph`.

**Comment by Edenharder** [comment]
@vtraag Thank you so much! It works. Previously, I forgot to uninstall these packages before the new installation.

**Comment by vtraag** [comment]
Great! This is the version that is currently under development, and if you encounter any issues, let us know!
