### ISSUE TITLE
Some methods are no longer in the documentation index

### ISSUE THREAD

**Issue by szhorvat** [igraph/python-igraph#471]
Many important methods are no longer included in the documentation index. Here are the reference docs:

https://igraph.org/python/api/latest/

This is the main index:

https://igraph.org/python/api/latest/nameIndex.html

I can no longer find `betweenness` or `shortest_paths` there. I think this happened after a recent doc update.

Ideally, there would be a main index where people can search for all concepts without having to understand the organization of the package first. Suppose you don't know igraph yet, but want to check if it supports concept X. It should be possible to just search for "X" in the main index.

**Comment by iosonofabio** [comment]
Thanks, could be due to the modularization. I'll take a look

**Comment by szhorvat** [comment]
I think this should be prioritized. It's a constant annoyance for me when searching the docs. I think it might be very frustrating for new users, or even worse:

If I they go to "A listing of all functions, classes, modules and packages, ordered by name. ", and do not find something, it is reasonable for them to assume that it does not exist. That is not the case though. The index is just incomplete.

**Comment by iosonofabio** [comment]
This is fixed in develop. These days I don't have time to backport to master, but if you want to try it should be doable

**Comment by szhorvat** [comment]
I am not familiar with the intricacies of the documentation system use for python-igraph. As you know, this is not where I contribute to igraph, and I do not think it is a good use of our collective time for another person to spend a few hours to learn it.

Is it difficult for you to fix this _on the website_, https://igraph.org/python/#docs? This is a major part of igraph's image, and a major contributor to any new user's first experience.

**Comment by ntamas** [comment]
I'll look into this next week; it seems like either it's not fixed on the `develop` branch either or something is wrong with the update mechanism on the site because I don't see `betweenness` or `shortest_paths` in the [index](https://igraph.org/python/api/develop/nameIndex.html).

**Comment by ntamas** [comment]
Okay, it seems like something is wrong on the homepage as running the documentation generation on the `develop` branch seems to work.

**Comment by iosonofabio** [comment]
it was part of the latest PR. There s a script (which you complained about already @ntamas :smirk: ) that de-modularized pure Python methods. In its original form, it missed classmethods, so porting that single file back to master might be a start.

That still does not explain why things like `betweenness` are missing, but I remember fighting with `pydoctor`'s "hide/show" feature (mainly through `__all__`) because underscore functions/modules are considered private and not shown by default. Now it seems like the current official docs on the website don't even show the "show private" button, so there might be a CSS/template issue there as well.

@ntamas let me know if this ends up being a nightmare and I'll take a look after you. Personally, I think we should prioritize releasing `0.10` so that this is fixed. Alternatively, we could merge `develop` into `master` now: that'll fix it on both branches at least.

**Comment by szhorvat** [comment]
> I think we should prioritize releasing `0.10` so that this is fixed

Regarding this:

It will take quite a while before the C core will be ready for a 0.10 release (several months at minimum). As I said in the chatroom, it seems to me that the motivation for wanting to release python-igraph 0.10 is coming from additions that have nothing to do with, and do not depends on the C core (plotting, tutorial, documentation). These should not force an unbaked C core release, nor do they need to: they can be included in a release based on C/igraph 0.9 (regardless of what version number python-igraph gets).

**Comment by iosonofabio** [comment]
I wish, but they also depend on the integer transition, which is why I'm pushy...

**Comment by ntamas** [comment]
This is now fixed with some CSS updates on the homepage.

**Comment by ntamas** [comment]
Also, @szhorvat, if you are working on the Dash docsets, this might have some relevance to you as well. Basically, the PyDoctor-generated pages use some JavaScript trickery to hide members that PyDoctor thinks are private by default. This is achieved by a JavaScript snippet that runs when the page is initialized; it checks whether the URL includes a specific parameter and if it doesn't, it adds a CSS class to the top-level `<body>` tag that hides the private members. I have overridden the corresponding CSS rules in our custom CSS so the effect does not take place, but it might be the case that it does not work in Dash. Or, it could be the case that Dash does not even run the JavaScript code and everything is visible by default, but the "Show/hide private  members" links won't do anything.

**Comment by ntamas** [comment]
Closing this as the original issue is now fixed on the homepage.
