### ISSUE TITLE
AttributeError: 'igraph.Edge' object has no attribute 'curved'

### ISSUE THREAD

**Issue by goldbattle** [igraph/python-igraph#535]
**Describe the bug**
I am getting this error
```
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    plot(g, out_name, **visual_style)
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 512, in plot
    result.save()
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 292, in save
    self.redraw()
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/drawing/__init__.py", line 276, in redraw
    plotter(ctx, bbox, palette, *args, **kwds)
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/__init__.py", line 4166, in __plot__
    drawer.draw(self, palette, *args, **kwds)
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/drawing/graph.py", line 489, in draw
    (x, y), (halign, valign) = edge_drawer.get_label_position(
  File "/home/patrick/.local/lib/python3.8/site-packages/igraph/drawing/edge.py", line 159, in get_label_position
    if edge.curved:
AttributeError: 'igraph.Edge' object has no attribute 'curved'
```

**To reproduce**
https://gist.github.com/goldbattle/bd020ca1039328250628c2a38aea90cd

**Version information**
Running Ubuntu 20.04 with python 3.8.
```
Requirement already satisfied: igraph in /home/<username>/.local/lib/python3.8/site-packages (0.9.10)
Requirement already satisfied: texttable>=1.6.2 in /usr/lib/python3/dist-packages (from igraph) (1.6.2)
```

**Comment by goldbattle** [comment]
I temporarily fixed it for myself by editing the file as follows (it seems the `curved` is never being initialized?):
https://gist.github.com/goldbattle/e55f232fe568b662b86a013f0533b946/revisions#diff-06651cdfa9a129d076d61773cf47a34ca5c89db399899ce0a6cd95db0c8fa19f

```diff
120c120
<         if edge.curved:
---
>         if hasattr(edge, 'curved') and edge.curved:
159c159
<         if edge.curved:
---
>         if hasattr(edge, 'curved') and edge.curved:
276c276
<         if edge.curved:
---
>         if hasattr(edge, 'curved') and edge.curved:
```

**Comment by ntamas** [comment]
Thanks for the patch. Can you confirm that you are using the Matplotlib drawing backend and not the Cairo backend?

**Comment by goldbattle** [comment]
How do I check this?

**Comment by ntamas** [comment]
Scratch that, I managed to reproduce this on my end with the Cairo backend. I'll commit a patch soon.

**Comment by ntamas** [comment]
Note to self: a more minimal example to reproduce the issue is as follows:

```python
from igraph import Graph, plot
g = Graph(5, directed=True)
g.add_edges([(0,2)])
g.es["label"] = [1]
plot(g)
```

**Comment by ntamas** [comment]
Fixed in 12cdfc6

**Comment by dsoprea** [comment]
Not yet released. Until then, this issue appears to not be present in 0.9.9 .

**Comment by cyberillion** [comment]
Issue still present in version 0.9.11.
I'm getting the  same error with almost the exact [reproduction](https://github.com/igraph/python-igraph/issues/535#issuecomment-1117865187):
```
from igraph import Graph, plot
g = Graph(5, directed=True)
g.add_edges([(0,2)])
g.es["label"] = [1]
plot(g).show() # Added show call to reproduce
```

**Comment by szhorvat** [comment]
This was released with 0.9.11. Double-check the version you are using. If you still see problems, please share a minimal example that demonstrates them.

**Comment by cyberillion** [comment]
You were right, this was a faulty package version inside venv, I
reinstalled the package and the bug disappeared - I removed my comment from
the discussion.
I'm very excited for new plotting features!

**Comment by highly0** [comment]
I'm still facing this issue. Not a single clue as to why its happening.

**Comment by szhorvat** [comment]
@highly0 Please show a [complete minimal example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem. Be sure to test with the latest version of python-igraph, 0.10.4
