### ISSUE TITLE
Error: AttributeError: 'str' object has no attribute 'arc'

### ISSUE THREAD

**Issue by BaseMax** [igraph/python-igraph#587]
**Describe the bug**
```
C:\Users\Max\Desktop\graphs-generation>python graphs.py
0.10.1
IGRAPH U--- 4 2 --
+ edges:
0--1 2--3
[[0, 1, 0, 0]
 [1, 0, 0, 0]
 [0, 0, 0, 1]
 [0, 0, 1, 0]]
Traceback (most recent call last):
  File "C:\Users\Max\Desktop\graphs-generation\graphs.py", line 12, in <module>
    ig.plot(g, "g.pdf")
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\__init__.py", line 245, in plot
    plotter(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\graph.py", line 558, in __plot__
    drawer.draw(self, *args, **kwds)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\matplotlib\graph.py", line 233, in draw
    drawer_method(visual_vertex, vertex, coords)
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\matplotlib\vertex.py", line 60, in draw
    stroke = visual_vertex.shape.draw_path(
  File "C:\Users\Max\AppData\Local\Programs\Python\Python310\lib\site-packages\igraph\drawing\shapes.py", line 168, in draw_path
    ctx.arc(center_x, center_y, width / 2, 0, 2 * pi)
AttributeError: 'str' object has no attribute 'arc'
```

**To reproduce**
```
import igraph as ig

print(ig.__version__)

g = ig.Graph(edges=[[0, 1], [2, 3]])

print(g)
print(g.get_adjacency())

ig.config['plotting.backend'] = 'matplotlib'
ig.plot(g)
ig.plot(g, "g.pdf")
```

**Version information**
0.10.1

**Comment by iosonofabio** [comment]
Thank you for reporting.

@ntamas didn't you just fix this one recently?

**Comment by iosonofabio** [comment]
@BaseMax This is a bug, thanks for digging it out.

Technically, I never thought of the possibility that someone might want to use `matplotlib` while also specifying a file as `target`. The `plot` function docstring is a little unclear but does hint to the fact that if you specify a string as a target, you'll be using Cairo instead of matplotlib. I'll improve the docs and logic a little so that you get matplotlib to store the figure using `fig.savefig` if a target is specified while using the matplotlib backend.

For practical purposes, I'd recommend you just plot using the following code:

```python
ig.plot(g).figure.savefig("g.pdf")
```

**Comment by ntamas** [comment]
> @ntamas didn't you just fix this one recently?

we fixed something similar (it might have been you, not me), but that one involved `igraph` mis-detecting that you were plotting on a Matplotlib context and it somehow used the Cairo backend -- but it didn't have a filename in the equation. It had to do something with the `isinstance()` checks that we were doing to detect Matplotlib figures _and_ the recent changes in Matplotlib 3.6.0 that somehow made these checks fail.

**Comment by BaseMax** [comment]
> @BaseMax This is a bug, thanks for digging it out.
> 
> Technically, I never thought of the possibility that someone might want to use `matplotlib` while also specifying a file as `target`. The `plot` function docstring is a little unclear but does hint to the fact that if you specify a string as a target, you'll be using Cairo instead of matplotlib. I'll improve the docs and logic a little so that you get matplotlib to store the figure using `fig.savefig` if a target is specified while using the matplotlib backend.
> 
> For practical purposes, I'd recommend you just plot using the following code:
> 
> ```python
> ig.plot(g).figure.savefig("g.pdf")
> ```


The following are working:

```
        # plt.savefig("output/" + name_parts[0] + "/" + final_file_name + ".pdf")
        # plt.savefig("output/" + name_parts[0] + "/" + final_file_name + ".png")
```

But your solution not works:

```
        ig.plot(g).figure.savefig("output/" + name_parts[0] + "/" + final_file_name + ".pdf")
        ig.plot(g).figure.savefig("output/" + name_parts[0] + "/" + final_file_name + ".png")
```

And the error:
```
Traceback (most recent call last):
  File "C:\Users\Max\Desktop\ConnectedQuarticGraphsPy\graphs.py", line 119, in <module>
    run_for_graphs(data, file_name)
  File "C:\Users\Max\Desktop\ConnectedQuarticGraphsPy\graphs.py", line 86, in run_for_graphs
    ig.plot(g).figure.savefig("output/" + name_parts[0] + "/" + final_file_name + ".pdf")
AttributeError: 'CairoPlot' object has no attribute 'figure'
```

**Comment by iosonofabio** [comment]
It works on my machine, I think you forgot to set the backend to matplotlib first. So you have to:

1. Set the backend to matplotlib
2. Plot without a target: the function returns an `Axes` which has the `figure` property which itself has the `savefig` method.

Alternatively, you can create your own matplotlib `Axes`:

```python
# No need to set the backend in this solution
import matplotlib.pyplot as plt

fig ,ax = plt.subplots()
ig.plot(g, target=ax)
fig.savefig('myfile.pdf')
```

In any case, I've made a PR that fixes the original bug, will be there in the next minor release I think. Thanks again for reporting.
